export const texts = {
  cart: 'Cart',
  cartWithCount: (count: number) => `Cart, ${count} ${count === 1 ? 'item' : 'items'}`,
  drawerTitle: (count: number) => `Your Cart (${count})`,
  closeCart: 'Close cart',
  pageTitle: 'Your Cart',
  home: 'Home',
  breadcrumbLabel: 'Breadcrumb',
  orderSummary: 'Order Summary',
  subtotal: 'Subtotal',
  shipping: 'Shipping',
  shippingAtCheckout: 'Calculated at checkout',
  total: 'Total',
  viewCart: 'View Cart',
  checkout: 'Checkout',
  checkoutSoon: 'Checkout is coming soon.',
  continueShopping: 'Continue Shopping',
  summaryNote: 'Taxes and shipping are calculated at checkout.',
  empty: 'Your cart is empty.',
  remove: 'Remove',
  removeItem: (name: string) => `Remove ${name}`,
  decrease: 'Decrease quantity',
  increase: 'Increase quantity',
  quantity: (name: string) => `Quantity of ${name}`,
  remaining: (amount: string) => `Add ${amount} more for free shipping.`,
  unlocked: "You've unlocked free shipping!",
  freeShippingProgress: 'Progress to free shipping',
  adjusted: (count: number) => `Only ${count} left — quantity updated.`,
  soldOut: 'Sold out',
  unavailable: 'This size is no longer available.',
  blocking: 'Remove unavailable items to continue.',
  removed: 'An item in your cart is no longer available and was removed.',
  updateFailed: "Couldn't update your cart. Try again.",
  loadFailed: "Your cart couldn't be loaded right now.",
  retry: 'Retry',
  loading: 'Loading your cart…',
};
