export const texts = {
  home: 'Home',
  breadcrumbLabel: 'Breadcrumb',
  unavailable: "This product couldn't be loaded right now.",
  fromTheShaper: 'From the shaper',
  readMore: 'Read more',
  readLess: 'Read less',
  attributes: 'Attributes',
  sections: { wave: 'Wave', performance: 'Performance', shape: 'Shape' },
  scales: {
    waveSize: { label: 'Size', scale: ['Knee', 'Double+'] },
    break: { label: 'Break', scale: ['Point', 'Reef', 'Beachbreak'] },
    power: { label: 'Power', scale: ['Weak / Mushy', 'Medium / Steep', 'Strong / Barrels'] },
    approach: { label: 'Approach', scale: ['Vertical / Pocket', 'Power / Carving', 'Cruisy / Positional'] },
    skillLevel: { label: 'Skill Level', scale: ['Beginner', 'Intermediate', 'Advanced'] },
    footOrientation: { label: 'Foot Orientation', scale: ['Back Foot', 'Neutral', 'Front Foot'] },
    foil: { label: 'Foil / Rails', scale: ['Thin', 'Medium', 'Full'] },
    noseShape: { label: 'Nose Shape', scale: ['Pointed', 'Hybrid', 'Round'] },
    tailWidth: { label: 'Tail Width', scale: ['Narrow', 'Medium', 'Wide'] },
    entryRocker: { label: 'Entry Rocker', scale: ['Relaxed', 'Medium', 'Aggressive'] },
    exitRocker: { label: 'Exit Rocker', scale: ['Relaxed', 'Medium', 'Aggressive'] },
    rockerStyle: { label: 'Rocker Style', scale: ['Staged', 'Continuous'] },
  },
  dimensions: 'Dimensions',
  soldOutOption: (label: string) => `${label} — Sold out`,
  addToCart: 'Add to Cart',
  soldOut: 'Sold out',
  trust: { shipping: 'Free shipping over $75', returns: '30-day returns', dispatch: 'Ships in 3–5 business days' },
  previousPhoto: 'Previous photo',
  nextPhoto: 'Next photo',
  openPhoto: (n: number, total: number) => `Open photo ${n} of ${total}`,
  photoViewer: 'Photo viewer',
  closePhotoViewer: 'Close photo viewer',
  photoCount: (n: number, total: number) => `${n} / ${total}`,
};
